# Generated by Django 3.0.8 on 2020-08-20 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_post_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_count',
        ),
    ]
