# Generated by Django 3.0.8 on 2020-08-22 20:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_post_cke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cke',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
