# Generated by Django 3.0.8 on 2020-08-22 20:50

import ckeditor.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20200822_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cke',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
