# Generated by Django 3.0.8 on 2020-08-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20200822_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cke',
        ),
    ]
