# Generated by Django 3.0.8 on 2020-08-22 20:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_post_cke'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cke',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
